[build]
  command = "npm --prefix artifacts/eleven-eleven ci && npm --prefix artifacts/eleven-eleven run check"
  publish = "artifacts/eleven-eleven/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
