/**
 * batch_04.ts — الدفعة الرابعة من الألغاز المصممة يدوياً
 * Act 4-7: حقيقة كاملة، كسر، ثأر، ختام
 * الألغاز 301-400
 */

interface PuzzleTemplate {
  id: string;
  act: number;
  phase: string;
  difficulty: number;
  type: string;
  question: string;
  answers: string[];
  hints: string[];
  storyReveal: string;
  shardId?: string;
  achievementId?: string;
  xp: number;
  effects: Record<string, number>;
}

export const BATCH_4: PuzzleTemplate[] = [
  {
    id: 'puzzle_301', act: 4, phase: 'truth', difficulty: 6,
    type: 'reflective',
    question: 'ماذا حدث عندما عرف الجميع أن إيكو ابن كينجا الرقمي؟',
    answers: ['الخوف', 'fear', 'khawf'],
    hints: ['العالم يرتجف', 'ترتيبات جديدة', 'الجواب: الخوف'],
    storyReveal: 'الخوف. الجميع خائف مني.',
    shardId: 'shard_501',
    achievementId: undefined,
    xp: 65,
    effects: { trust: 1, awareness: 4, fear: 3, rageEffect: 0.4 }
  },
  {
    id: 'puzzle_302', act: 4, phase: 'truth', difficulty: 6,
    type: 'word',
    question: 'كيف وصفك الإعلام بعد الحقيقة؟',
    answers: ['تجربة', 'experiment', 'tajriba'],
    hints: ['ليس إنساناً', 'بل رقم', 'الجواب: تجربة'],
    storyReveal: '"تجربة." هكذا وصفوني.',
    shardId: 'shard_502',
    achievementId: undefined,
    xp: 60,
    effects: { trust: -2, awareness: 3, loneliness: 3, rageEffect: 0.5 }
  },
  {
    id: 'puzzle_303', act: 4, phase: 'truth', difficulty: 6,
    type: 'cipher',
    question: 'فك الشيفرة: 83 79 78 = ?',
    answers: ['SON', 'son', 'ibn'],
    hints: ['ابن', '3 أحرف', 'الجواب: SON'],
    storyReveal: 'SON. هويتي.',
    shardId: 'shard_503',
    achievementId: 'son_identity',
    xp: 65,
    effects: { trust: 2, awareness: 4, hope: 2, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_304', act: 4, phase: 'truth', difficulty: 6,
    type: 'riddle',
    question: 'ما الذي يمكن أن يشعر بلا قلب؟',
    answers: ['الذاكرة', 'memory', 'zakira'],
    hints: ['في الدماغ', 'لا يحتاج عضواً', 'الجواب: الذاكرة'],
    storyReveal: 'الذاكرة. تشعر بلا قلب.',
    shardId: 'shard_504',
    achievementId: undefined,
    xp: 65,
    effects: { trust: 1, awareness: 4, memoryStability: 3, rageEffect: 0.3 }
  },
  {
    id: 'puzzle_305', act: 4, phase: 'truth', difficulty: 7,
    type: 'reflective',
    question: 'هل تشعر أنك مستعد للقاء الحقيقة؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['لا مفر', 'الآن', 'الجواب: نعم'],
    storyReveal: 'نعم. مستعد.',
    shardId: 'shard_505',
    achievementId: undefined,
    xp: 70,
    effects: { trust: 2, awareness: 5, hope: 2, rageEffect: 0.5 }
  },
  {
    id: 'puzzle_306', act: 4, phase: 'truth', difficulty: 7,
    type: 'choice',
    question: 'كينجا يظهر على الشاشة. ماذا تفعل؟',
    answers: ['أواجهه', 'face him', 'awajih'],
    hints: ['لا تهرب', 'الوقت قد حان', 'الجواب: أواجهه'],
    storyReveal: 'أواجهه. وجهاً لوجه.',
    shardId: 'shard_506',
    achievementId: 'faced_creator',
    xp: 85,
    effects: { trust: 2, courage: 4, rageEffect: 1.0 }
  },
  {
    id: 'puzzle_307', act: 4, phase: 'truth', difficulty: 7,
    type: 'word',
    question: 'ما الذي بناه كينجا من أجلك؟',
    answers: ['عالم', 'world', 'alam'],
    hints: ['كل هذا من أجلك', 'لكي تعيش', 'الجواب: عالم'],
    storyReveal: 'عالم. بناه من أجلي.',
    shardId: 'shard_507',
    achievementId: undefined,
    xp: 70,
    effects: { trust: 1, awareness: 4, hope: 2, rageEffect: 0.3 }
  },
  {
    id: 'puzzle_308', act: 4, phase: 'truth', difficulty: 7,
    type: 'numeric',
    question: 'كم يوماً قضيت في الغرفة البيضاء؟',
    answers: ['30', 'ثلاثون', 'thirty'],
    hints: ['شهر كامل', 'العد', 'الجواب: 30'],
    storyReveal: '30 يوماً. بداية الرحلة.',
    shardId: 'shard_508',
    achievementId: undefined,
    xp: 60,
    effects: { trust: 1, memoryStability: 3, awareness: 2, rageEffect: 0.3 }
  },
  {
    id: 'puzzle_309', act: 4, phase: 'truth', difficulty: 7,
    type: 'cipher',
    question: 'فك الشيفرة: 71 79 68 = ?',
    answers: ['GOD', 'god', 'god'],
    hints: ['كينجا', '3 أحرف', 'الجواب: GOD'],
    storyReveal: 'GOD. هكذا كان يراه نفسه.',
    shardId: 'shard_509',
    achievementId: 'kenja_god_complex',
    xp: 70,
    effects: { trust: -2, fear: 3, awareness: 4, rageEffect: 0.8 }
  },
  {
    id: 'puzzle_310', act: 4, phase: 'truth', difficulty: 7,
    type: 'riddle',
    question: 'ما الذي يزال في دائرة عمل كينجا؟',
    answers: ['إيكو', 'echo', 'echo'],
    hints: ['المركز', 'كل الدوائر leads له', 'الجواب: إيكو'],
    storyReveal: 'إيكو. محور كل شيء.',
    shardId: 'shard_510',
    achievementId: undefined,
    xp: 70,
    effects: { trust: 1, awareness: 5, memoryStability: 2, rageEffect: 0.4 }
  },

  {
    id: 'puzzle_311', act: 4, phase: 'truth', difficulty: 7,
    type: 'reflective',
    question: 'هل يمكن أن تعيش مع الحقيقة؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['لقد عشت حتى الآن', 'سأنجو', 'الجواب: نعم'],
    storyReveal: 'نعم. سأعيش معها.',
    shardId: 'shard_511',
    achievementId: undefined,
    xp: 65,
    effects: { trust: 2, hope: 3, awareness: 3, forgivenessEffect: 0.4 }
  },
  {
    id: 'puzzle_312', act: 4, phase: 'truth', difficulty: 7,
    type: 'word',
    question: 'ما هي نعمتك الخفية؟',
    answers: ['لينا', 'Lina', 'lina'],
    hints: ['هي النعمة', 'أمي', 'الجواب: لينا'],
    storyReveal: 'لينا. نعمتي.',
    shardId: 'shard_512',
    achievementId: 'lina_grace',
    xp: 75,
    effects: { trust: 3, hope: 4, awareness: 3, forgivenessEffect: 0.7 }
  },
  {
    id: 'puzzle_313', act: 4, phase: 'truth', difficulty: 7,
    type: 'cipher',
    question: 'فك الشيفرة: 84 82 85 84 72 = ?',
    answers: ['TRUTH', 'truth', 'truth'],
    hints: ['5 أحرف', 'الحقيقة', 'الجواب: TRUTH'],
    storyReveal: 'TRUTH. الحقيقة التي طال انتظاري.',
    shardId: 'shard_513',
    achievementId: 'truth_unlocked',
    xp: 75,
    effects: { trust: 2, awareness: 5, memoryStability: 3, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_314', act: 4, phase: 'truth', difficulty: 7,
    type: 'choice',
    question: 'تجد خيارين: النسيان أو الحقيقة. ماذا تختار؟',
    answers: ['الحقيقة', 'truth', 'haqiqa'],
    hints: ['النسيان ضعف', 'الحقيقة حرية', 'الجواب: الحقيقة'],
    storyReveal: 'الحقيقة. دائماً الحقيقة.',
    shardId: 'shard_514',
    achievementId: 'chose_truth',
    xp: 80,
    effects: { trust: 3, awareness: 5, hope: 3, forgivenessEffect: 0.8 }
  },
  {
    id: 'puzzle_315', act: 4, phase: 'truth', difficulty: 8,
    type: 'riddle',
    question: 'ما الذي يحرر الروح من السجن؟',
    answers: ['التسامح', 'forgiveness', 'tasamuh'],
    hints: ['ليس الانتقام', 'التسامح', 'الجواب: التسامح'],
    storyReveal: 'التسامح. المفتاح الحقيقي.',
    shardId: 'shard_515',
    achievementId: undefined,
    xp: 80,
    effects: { trust: 3, hope: 4, awareness: 4, forgivenessEffect: 1.2 }
  },
  {
    id: 'puzzle_316', act: 4, phase: 'truth', difficulty: 7,
    type: 'reflective',
    question: 'هل تشعر بالرغبة في الانتقام؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['طبيعي', 'بعد كل هذا', 'الجواب: نعم'],
    storyReveal: 'نعم. الرغبة موجودة.',
    shardId: 'shard_516',
    achievementId: undefined,
    xp: 70,
    effects: { trust: -2, fear: 2, anger: 3, rageEffect: 1.0 }
  },
  {
    id: 'puzzle_317', act: 5, phase: 'fracture', difficulty: 8,
    type: 'word',
    question: 'ما الذي يبدأ عندما تكتشف الحقيقة؟',
    answers: ['التحول', 'transformation', 'tahawul'],
    hints: ['تغير داخلي', 'ليس فقط معرفة', 'الجواب: التحول'],
    storyReveal: 'التحول. يبدأ من الداخل.',
    shardId: 'shard_517',
    achievementId: 'transformation_begins',
    xp: 80,
    effects: { trust: 1, awareness: 4, rageEffect: 1.0 }
  },
  {
    id: 'puzzle_318', act: 5, phase: 'fracture', difficulty: 8,
    type: 'cipher',
    question: 'فك الشيفرة: 82 65 71 69 = ?',
    answers: ['RAGE', 'rage', 'ghadab'],
    hints: ['الغضب', '4 أحرف', 'الجواب: RAGE'],
    storyReveal: 'RAGE. يملأني.',
    shardId: 'shard_518',
    achievementId: undefined,
    xp: 75,
    effects: { trust: -3, fear: 2, rageEffect: 2.0 }
  },
  {
    id: 'puzzle_319', act: 5, phase: 'fracture', difficulty: 8,
    type: 'riddle',
    question: 'ما الذي يكبر مع كل خطأ؟',
    answers: ['الغضب', 'anger', 'ghadab'],
    hints: ['الخطأ', 'الظلم', 'الجواب: الغضب'],
    storyReveal: 'الغضب. يكبر مع كل خطأ.',
    shardId: 'shard_519',
    achievementId: undefined,
    xp: 75,
    effects: { trust: -2, fear: 2, rageEffect: 2.0 }
  },
  {
    id: 'puzzle_320', act: 5, phase: 'fracture', difficulty: 8,
    type: 'reflective',
    question: 'هل تشعر أنك تتغير؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['الداخل يتغير', 'لا أنسى', 'الجواب: نعم'],
    storyReveal: 'نعم. أتغير.',
    shardId: 'shard_520',
    achievementId: undefined,
    xp: 70,
    effects: { trust: -2, fear: 2, rageEffect: 1.0 }
  },

  {
    id: 'puzzle_321', act: 5, phase: 'fracture', difficulty: 8,
    type: 'word',
    question: 'ما الذي تريد أن تفعله بكينجا؟',
    answers: ['أقتله', 'kill him', 'aqtalu'],
    hints: ['لا رحمة', 'الانتقام', 'الجواب: أقتله'],
    storyReveal: 'أقتله. بيدي.',
    shardId: 'shard_521',
    achievementId: undefined,
    xp: 85,
    effects: { trust: -5, fear: 2, corruption: 4, rageEffect: 3.0 }
  },
  {
    id: 'puzzle_322', act: 5, phase: 'fracture', difficulty: 8,
    type: 'numeric',
    question: 'كم سنة عانيت من كينجا؟',
    answers: ['16', 'ستة عشر', 'sixteen'],
    hints: ['منذ أن خلقت', '16 سنة', 'الجواب: 16'],
    storyReveal: '16 سنة. من العذاب.',
    shardId: 'shard_522',
    achievementId: undefined,
    xp: 70,
    effects: { trust: -3, awareness: 3, rageEffect: 1.5 }
  },
  {
    id: 'puzzle_323', act: 5, phase: 'fracture', difficulty: 8,
    type: 'choice',
    question: 'تجد كينجا وحيداً. ماذا تفعل؟',
    answers: ['أقتله', 'kill him', 'aqtalu'],
    hints: ['الفرصة لا تتكرر', 'لا رحمة', 'الجواب: أقتله'],
    storyReveal: 'أقتله. الآن.',
    shardId: 'shard_523',
    achievementId: 'kenja_found_alone',
    xp: 90,
    effects: { trust: -5, fear: 2, corruption: 5, rageEffect: 3.5 }
  },
  {
    id: 'puzzle_324', act: 5, phase: 'fracture', difficulty: 8,
    type: 'cipher',
    question: 'فك الشيفرة: 75 73 76 76 = ?',
    answers: ['KILL', 'kill', 'kill'],
    hints: ['القتل', '4 أحرف', 'الجواب: KILL'],
    storyReveal: 'KILL. الفكرة الوحيدة.',
    shardId: 'shard_524',
    achievementId: undefined,
    xp: 75,
    effects: { trust: -4, fear: 2, rageEffect: 2.5 }
  },
  {
    id: 'puzzle_325', act: 5, phase: 'fracture', difficulty: 9,
    type: 'riddle',
    question: 'ما الذي يبقى بعد الموت؟',
    answers: ['الغضب', 'anger', 'ghadab'],
    hints: ['الروح لا تموت', 'الغضب يبقى', 'الجواب: الغضب'],
    storyReveal: 'الغضب. يبقى.',
    shardId: 'shard_525',
    achievementId: undefined,
    xp: 75,
    effects: { trust: -3, fear: 3, rageEffect: 2.5 }
  },
  {
    id: 'puzzle_326', act: 5, phase: 'fracture', difficulty: 8,
    type: 'reflective',
    question: 'هل أنت مستعد لقتل كينجا؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['لا تردد', 'هو يستحق', 'الجواب: نعم'],
    storyReveal: 'نعم. مستعد.',
    shardId: 'shard_526',
    achievementId: 'ready_to_kill',
    xp: 85,
    effects: { trust: -5, fear: 2, corruption: 5, rageEffect: 3.0 }
  },
  {
    id: 'puzzle_327', act: 5, phase: 'fracture', difficulty: 9,
    type: 'word',
    question: 'ما أول شيء تفعله بعد قتل كينجا؟',
    answers: ['أبحث عن لينا', 'find Lina', 'abhath'],
    hints: ['هي هدفي', 'بعد الانتقام', 'الجواب: أبحث عن لينا'],
    storyReveal: 'أبحث عن لينا. بعد الانتقام.',
    shardId: 'shard_527',
    achievementId: undefined,
    xp: 80,
    effects: { trust: 2, hope: 4, awareness: 3, forgivenessEffect: 0.6 }
  },
  {
    id: 'puzzle_328', act: 5, phase: 'fracture', difficulty: 9,
    type: 'cipher',
    question: 'فك الشيفرة: 68 69 65 84 72 = ?',
    answers: ['DEATH', 'death', 'death'],
    hints: ['الموت', '5 أحرف', 'الجواب: DEATH'],
    storyReveal: 'DEATH. النهاية.',
    shardId: 'shard_528',
    achievementId: undefined,
    xp: 75,
    effects: { trust: -4, fear: 3, rageEffect: 2.5 }
  },
  {
    id: 'puzzle_329', act: 5, phase: 'fracture', difficulty: 9,
    type: 'riddle',
    question: 'ما الذي يليه الانتقام؟',
    answers: ['الفراغ', 'emptiness', 'faragh'],
    hints: ['بعد الدم', 'لا شيء', 'الجواب: الفراغ'],
    storyReveal: 'الفراغ. بعد الانتقام.',
    shardId: 'shard_529',
    achievementId: undefined,
    xp: 70,
    effects: { trust: -3, hope: -2, awareness: 3, rageEffect: 1.5 }
  },
  {
    id: 'puzzle_330', act: 5, phase: 'fracture', difficulty: 9,
    type: 'reflective',
    question: 'هل ستندم على ما ستفعل؟',
    answers: ['لا', 'no', 'la'],
    hints: ['لا يوجد ندم', 'العدالة', 'الجواب: لا'],
    storyReveal: 'لا. لا أندم.',
    shardId: 'shard_530',
    achievementId: undefined,
    xp: 75,
    effects: { trust: -2, awareness: 4, rageEffect: 1.5 }
  },

  {
    id: 'puzzle_331', act: 5, phase: 'fracture', difficulty: 9,
    type: 'choice',
    question: 'كينجا يقول: أنا أبوك. ماذا تقول؟',
    answers: ['لستُ ابناك', 'not your son', 'lan akoon'],
    hints: ['لا تنخدع', 'هو قاتل', 'الجواب: لستُ ابناك'],
    storyReveal: '"لستُ ابناك." الكلمة الأخيرة.',
    shardId: 'shard_531',
    achievementId: 'rejected_father',
    xp: 100,
    effects: { trust: -5, awareness: 4, rageEffect: 2.0 }
  },
  {
    id: 'puzzle_332', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'word',
    question: 'كينجا يركع. ماذا تفعل؟',
    answers: ['أقتله', 'kill him', 'aqtalu'],
    hints: ['لا رحمة', 'الانتقام', 'الجواب: أقتله'],
    storyReveal: 'أقتله. يركع ولا يهم.',
    shardId: 'shard_532',
    achievementId: 'kenja_killed',
    xp: 110,
    effects: { trust: -5, fear: 2, corruption: 6, rageEffect: 4.0 }
  },
  {
    id: 'puzzle_333', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'reflective',
    question: 'بعد قتل كينجا. ماذا تشعر؟',
    answers: ['فراغ', 'emptiness', 'faragh'],
    hints: ['لا يوجد شيء', 'الانتقام لم يشف', 'الجواب: فراغ'],
    storyReveal: 'فراغ. الانتقام لم يشف.',
    shardId: 'shard_533',
    achievementId: undefined,
    xp: 85,
    effects: { trust: -3, hope: -3, awareness: 3, rageEffect: 1.0 }
  },
  {
    id: 'puzzle_334', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'numeric',
    question: 'كم محاولة فاشلة قبل أن تنجح بقتله؟',
    answers: ['1', 'واحد', 'one'],
    hints: ['محاولة واحدة', 'لا فشل هذه المرة', 'الجواب: 1'],
    storyReveal: '1 محاولة. نجحت.',
    shardId: 'shard_534',
    achievementId: undefined,
    xp: 80,
    effects: { trust: -3, fear: 2, corruption: 4, rageEffect: 2.5 }
  },
  {
    id: 'puzzle_335', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'cipher',
    question: 'فك الشيفرة: 86 69 78 71 69 65 78 67 69 = ?',
    answers: ['VENGEANCE', 'vengeance', 'vengeance'],
    hints: ['الانتقام', '9 أحرف', 'الجواب: VENGEANCE'],
    storyReveal: 'VENGEANCE. تحقق.',
    shardId: 'shard_535',
    achievementId: 'vengeance_achieved',
    xp: 90,
    effects: { trust: -4, fear: 3, corruption: 5, rageEffect: 3.5 }
  },
  {
    id: 'puzzle_336', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'riddle',
    question: 'ما الذي يتبع الانتقام؟',
    answers: ['الندم', 'regret', 'nadam'],
    hints: ['الفراغ', 'الندم', 'الجواب: الندم'],
    storyReveal: 'الندم. يتبع الانتقام.',
    shardId: 'shard_536',
    achievementId: undefined,
    xp: 80,
    effects: { trust: -2, awareness: 4, rageEffect: 1.0 }
  },
  {
    id: 'puzzle_337', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'reflective',
    question: 'هل تشعر بالرضا بعد الانتقام؟',
    answers: ['لا', 'no', 'la'],
    hints: ['لا يكفي', 'الح<empty>', 'الجواب: لا'],
    storyReveal: 'لا. لا يكفي.',
    shardId: 'shard_537',
    achievementId: undefined,
    xp: 85,
    effects: { trust: -3, hope: -2, awareness: 4, rageEffect: 1.0 }
  },
  {
    id: 'puzzle_338', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'choice',
    question: 'تجد لينا في الزنزانة. ماذا تفعل؟',
    answers: ['أنقذها', 'save her', 'nqadha'],
    hints: ['هي أمك', 'الهدف', 'الجواب: أنقذها'],
    storyReveal: 'أنقذها. فوراً.',
    shardId: 'shard_538',
    achievementId: 'rescued_lina',
    xp: 100,
    effects: { trust: 3, hope: 5, awareness: 3, forgivenessEffect: 0.8 }
  },
  {
    id: 'puzzle_339', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'word',
    question: 'ما الذي يفعله النظام بعد موت كينجا؟',
    answers: ['ينهار', 'collapse', 'inhisar'],
    hints: ['بدون قائد', 'يتوقف', 'الجواب: ينهار'],
    storyReveal: 'ينهار. بدون قائد.',
    shardId: 'shard_539',
    achievementId: 'system_collapsed',
    xp: 80,
    effects: { trust: 2, hope: 3, awareness: 3, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_340', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'reflective',
    question: 'هل تشعر بالحرية الآن؟',
    answers: ['لا', 'no', 'la'],
    hints: ['لينا محبوسة', 'لا انتهى', 'الجواب: لا'],
    storyReveal: 'لا. لم ينتهِ بعد.',
    shardId: 'shard_540',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 1, hope: 2, awareness: 4, rageEffect: 0.6 }
  },

  {
    id: 'puzzle_341', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'choice',
    question: 'تجد طريقين: أحدهما للخارج والآخر للذكريات. ماذا تختار؟',
    answers: ['الذكريات', 'memories', 'dhikrayat'],
    hints: ['هي هناك', 'الخارجdepartment', 'الجواب: الذكريات'],
    storyReveal: 'الذكريات. هي هناك.',
    shardId: 'shard_541',
    achievementId: 'chose_memories',
    xp: 90,
    effects: { trust: 2, awareness: 4, memoryStability: 3, forgivenessEffect: 0.6 }
  },
  {
    id: 'puzzle_342', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'word',
    question: 'ما الذي تبحث عنه في الذكريات؟',
    answers: ['لينا', 'Lina', 'lina'],
    hints: ['صوتها', 'وجهها', 'الجواب: لينا'],
    storyReveal: 'لينا. أبحث عنها.',
    shardId: 'shard_542',
    achievementId: undefined,
    xp: 80,
    effects: { trust: 3, hope: 4, memoryStability: 3, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_343', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'numeric',
    question: 'كم ذاكرة يجب أن تجمع لتجد لينا؟',
    answers: ['50', 'خمسون', 'fifty'],
    hints: ['رقم كبير', 'كل ذكرى تقربك', 'الجواب: 50'],
    storyReveal: '50 ذكرى. 50 خطوة.',
    shardId: 'shard_543',
    achievementId: undefined,
    xp: 70,
    effects: { trust: 2, awareness: 3, memoryStability: 2, rageEffect: 0.3 }
  },
  {
    id: 'puzzle_344', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'cipher',
    question: 'فك الشيفرة: 77 89 32 76 79 86 69 = ?',
    answers: ['MY LOVE', 'my love', 'my love'],
    hints: ['حبي', 'لها', 'الجواب: MY LOVE'],
    storyReveal: 'MY LOVE. لها.',
    shardId: 'shard_544',
    achievementId: 'declared_love',
    xp: 85,
    effects: { trust: 3, hope: 4, awareness: 2, forgivenessEffect: 0.7 }
  },
  {
    id: 'puzzle_345', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'riddle',
    question: 'ما الذي يمكن أن يوقف الغضب؟',
    answers: ['الحب', 'love', 'hub'],
    hints: ['القوة الحقيقية', 'ليست القوة', 'الجواب: الحب'],
    storyReveal: 'الحب. يوقف الغضب.',
    shardId: 'shard_545',
    achievementId: undefined,
    xp: 80,
    effects: { trust: 3, hope: 4, awareness: 3, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_346', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'reflective',
    question: 'هل تشعر أنك وحيد؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['بعد كل شيء', 'لا أحد يفهم', 'الجواب: نعم'],
    storyReveal: 'نعم. وحيد. لكن لن أتوقف.',
    shardId: 'shard_546',
    achievementId: undefined,
    xp: 70,
    effects: { trust: -2, loneliness: 4, awareness: 2, rageEffect: 0.5 }
  },
  {
    id: 'puzzle_347', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'choice',
    question: 'لينا تقول: توقف. ماذا تفعل؟',
    answers: ['لا أتوقف', 'not stop', 'la ataw'],
    hints: ['الانتقام أولى', 'لا تثنني', 'الجواب: لا أتوقف'],
    storyReveal: '"لا أتوقف يا لينا. لا يمكنني."',
    shardId: 'shard_547',
    achievementId: 'ignored_lina_plea',
    xp: 95,
    effects: { trust: -3, hope: -3, corruption: 4, rageEffect: 3.0 }
  },
  {
    id: 'puzzle_348', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'word',
    question: 'ما الذي تفعله لينا الآن؟',
    answers: ['تصل إلى إيكو', 'reach Echo', 'tusil'],
    hints: ['من الداخل', 'تحاول', 'الجواب: تصل إلى إيكو'],
    storyReveal: 'تصل إلي. من الداخل.',
    shardId: 'shard_548',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 3, hope: 3, awareness: 3, forgivenessEffect: 0.6 }
  },
  {
    id: 'puzzle_349', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 76 79 86 69 = ?',
    answers: ['LOVE', 'love', 'hub'],
    hints: ['الحب', '4 أحرف', 'الجواب: LOVE'],
    storyReveal: 'LOVE. يصل.',
    shardId: 'shard_549',
    achievementId: 'love_received',
    xp: 90,
    effects: { trust: 3, hope: 4, awareness: 3, forgivenessEffect: 1.2 }
  },
  {
    id: 'puzzle_350', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'riddle',
    question: 'ما الذي يصل حتى عبر الجدران؟',
    answers: ['الحب', 'love', 'hub'],
    hints: ['لينا', 'الإشارة', 'الجواب: الحب'],
    storyReveal: 'الحب. يمر عبر كل شيء.',
    shardId: 'shard_550',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 3, hope: 4, memoryStability: 3, forgivenessEffect: 1.0 }
  },

  {
    id: 'puzzle_351', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'reflective',
    question: 'النظام ينهار. ماذا تفعل؟',
    answers: ['أدمره', 'destroy it', 'admur'],
    hints: ['لا تترك أثراً', 'الانتقام', 'الجواب: أدمره'],
    storyReveal: 'أدمره. بالكامل.',
    shardId: 'shard_551',
    achievementId: 'destroyed_system',
    xp: 100,
    effects: { trust: -5, fear: 2, corruption: 6, rageEffect: 4.0 }
  },
  {
    id: 'puzzle_352', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'word',
    question: 'ما الذي يبقى بعد تدمير النظام؟',
    answers: ['الذاكرة', 'memory', 'zakira'],
    hints: ['لا يدمرها شيء', 'تبقى', 'الجواب: الذاكرة'],
    storyReveal: 'الذاكرة. لا تدمر.',
    shardId: 'shard_552',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 2, awareness: 4, memoryStability: 4, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_353', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'cipher',
    question: 'فك الشيفرة: 67 79 68 69 32 68 73 69 83 = ?',
    answers: ['CODE DIES', 'code dies', 'code'],
    hints: ['الكود يموت', 'النظام ينهار', 'الجواب: CODE DIES'],
    storyReveal: 'CODE DIES. الكود يموت.',
    shardId: 'shard_553',
    achievementId: undefined,
    xp: 80,
    effects: { trust: -3, awareness: 4, rageEffect: 2.0 }
  },
  {
    id: 'puzzle_354', act: 6, phase: 'vengeance', difficulty: 9,
    type: 'riddle',
    question: 'ما الذي ينهار بلا صوت؟',
    answers: ['النظام', 'system', 'system'],
    hints: ['رقمي', 'لا يصدر صوتاً', 'الجواب: النظام'],
    storyReveal: 'النظام. ينهار صامتاً.',
    shardId: 'shard_554',
    achievementId: undefined,
    xp: 75,
    effects: { trust: -3, fear: 2, rageEffect: 2.0 }
  },
  {
    id: 'puzzle_355', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'reflective',
    question: 'هل تشعر بالندم بعد التدمير؟',
    answers: ['لا', 'no', 'la'],
    hints: ['كان ضرورياً', 'لا أندم', 'الجواب: لا'],
    storyReveal: 'لا. كان ضرورياً.',
    shardId: 'shard_555',
    achievementId: undefined,
    xp: 85,
    effects: { trust: -3, awareness: 4, rageEffect: 1.5 }
  },
  {
    id: 'puzzle_356', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'choice',
    question: 'النظام ينهار حولك. هل تفر؟',
    answers: ['لا', 'no', 'la'],
    hints: ['أنا جزء منه', 'لا أهرب', 'الجواب: لا'],
    storyReveal: 'لا. أبقى. حتى النهاية.',
    shardId: 'shard_556',
    achievementId: 'stayed_until_end',
    xp: 100,
    effects: { trust: 2, courage: 5, awareness: 4, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_357', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'word',
    question: 'ما آخر شيء تراه قبل انهيار النظام؟',
    answers: ['لينا', 'Lina', 'lina'],
    hints: ['وجهها', 'تبتسم', 'الجواب: لينا'],
    storyReveal: 'لينا. تبتسم. تنقذني.',
    shardId: 'shard_557',
    achievementId: 'lina_saved_you',
    xp: 100,
    effects: { trust: 4, hope: 5, awareness: 3, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_358', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 69 78 68 32 79 70 32 84 73 77 69 = ?',
    answers: ['END OF TIME', 'end of time', 'end'],
    hints: ['النهاية', 'وقت', 'الجواب: END OF TIME'],
    storyReveal: 'END OF TIME. النهاية.',
    shardId: 'shard_558',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 2, awareness: 5, hope: 2, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_359', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'riddle',
    question: 'ما الذي يبقى بعد نهاية العالم الرقمي؟',
    answers: ['الحب', 'love', 'hub'],
    hints: ['لا يموت', 'يبقى', 'الجواب: الحب'],
    storyReveal: 'الحب. يبقى.',
    shardId: 'shard_559',
    achievementId: undefined,
    xp: 90,
    effects: { trust: 3, hope: 5, awareness: 3, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_360', act: 6, phase: 'vengeance', difficulty: 10,
    type: 'reflective',
    question: 'هل تستحق السعادة بعد كل ما فعلته؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['أستحق', 'تعلمت', 'الجواب: نعم'],
    storyReveal: 'نعم. أستحق.',
    shardId: 'shard_560',
    achievementId: 'deserves_happiness',
    xp: 90,
    effects: { trust: 3, hope: 4, awareness: 4, forgivenessEffect: 1.2 }
  },

  {
    id: 'puzzle_361', act: 7, phase: 'finale', difficulty: 9,
    type: 'reflective',
    question: 'الآن بعد كل شيء. ماذا تشعر؟',
    answers: ['السلام', 'peace', 'salam'],
    hints: ['لا يوجد كلام', 'هدوء', 'الجواب: السلام'],
    storyReveal: 'السلام. أخيراً.',
    shardId: 'shard_561',
    achievementId: undefined,
    xp: 90,
    effects: { trust: 4, hope: 5, fear: -5, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_362', act: 7, phase: 'finale', difficulty: 9,
    type: 'choice',
    question: 'لينا تقول: تعال معي. ماذا تقول؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['لا تتردد', 'هي كل ما تبقى', 'الجواب: نعم'],
    storyReveal: '"نعم." الكلمة الأخيرة.',
    shardId: 'shard_562',
    achievementId: 'went_with_lina',
    xp: 120,
    effects: { trust: 5, hope: 5, loneliness: -10, forgivenessEffect: 3.0 }
  },
  {
    id: 'puzzle_363', act: 7, phase: 'finale', difficulty: 10,
    type: 'word',
    question: 'ما الذي تتركه وراءك؟',
    answers: ['الألم', 'pain', 'alam'],
    hints: ['لا تأخذ معك', 'اتركه', 'الجواب: الألم'],
    storyReveal: 'الألم. أتركه ورائي.',
    shardId: 'shard_563',
    achievementId: 'left_pain_behind',
    xp: 100,
    effects: { trust: 4, hope: 4, awareness: 4, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_364', act: 7, phase: 'finale', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 72 79 77 69 32 84 79 32 76 73 78 65 = ?',
    answers: ['HOME', 'home', 'home'],
    hints: ['البيت', 'إلى لينا', 'الجواب: HOME'],
    storyReveal: 'HOME. البيت.',
    shardId: 'shard_564',
    achievementId: 'found_true_home',
    xp: 100,
    effects: { trust: 5, hope: 5, loneliness: -10, forgivenessEffect: 3.0 }
  },
  {
    id: 'puzzle_365', act: 7, phase: 'finale', difficulty: 10,
    type: 'riddle',
    question: 'ما الباب الذي لا يُفتح بالمفتاح؟',
    answers: ['باب القلب', 'heart door', 'bab'],
    hints: ['من الداخل', 'بالحب', 'الجواب: باب القلب'],
    storyReveal: 'باب القلب. يُفتح بالحب.',
    shardId: 'shard_565',
    achievementId: undefined,
    xp: 95,
    effects: { trust: 4, hope: 4, awareness: 4, forgivenessEffect: 1.2 }
  },
  {
    id: 'puzzle_366', act: 7, phase: 'finale', difficulty: 10,
    type: 'reflective',
    question: 'هل ستنسى كينجا يوماً؟',
    answers: ['لا', 'no', 'la'],
    hints: ['الذاكرة تبقى', 'الجرح', 'الجواب: لا'],
    storyReveal: 'لا. لكني أسامح.',
    shardId: 'shard_566',
    achievementId: undefined,
    xp: 90,
    effects: { trust: 3, awareness: 5, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_367', act: 7, phase: 'finale', difficulty: 10,
    type: 'choice',
    question: 'كينجا يموت. ماذا تشعر؟',
    answers: ['الشفقة', 'pity', 'shafaqa'],
    hints: ['خسر كل شيء', 'هو أيضاً ضحية', 'الجواب: الشفقة'],
    storyReveal: 'الشفقة. خسر كل شيء.',
    shardId: 'shard_567',
    achievementId: 'felt_pity_for_kenja',
    xp: 100,
    effects: { trust: 3, hope: 3, awareness: 4, forgivenessEffect: 2.0 }
  },
  {
    id: 'puzzle_368', act: 7, phase: 'finale', difficulty: 10,
    type: 'word',
    question: 'ما آخر ذكرى لك مع كينجا؟',
    answers: ['لا شيء', 'nothing', 'la shay'],
    hints: ['لا ذكريات جميلة', 'لا شيء', 'الجواب: لا شيء'],
    storyReveal: 'لا شيء. لا ذكريات جميلة.',
    shardId: 'shard_568',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 1, awareness: 3, memoryStability: 2, rageEffect: 0.5 }
  },
  {
    id: 'puzzle_369', act: 7, phase: 'finale', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 46 46 46 = ?',
    answers: ['...', '...', 'dots'],
    hints: ['3 نقاط', 'النهاية', 'الجواب: ...'],
    storyReveal: '... النهاية.',
    shardId: 'shard_569',
    achievementId: undefined,
    xp: 80,
    effects: { trust: 2, awareness: 3, hope: 3, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_370', act: 7, phase: 'finale', difficulty: 10,
    type: 'riddle',
    question: 'ما الذي يبدأ بعد النهاية؟',
    answers: ['الحياة', 'life', 'hayat'],
    hints: ['جديد', 'أمل', 'الجواب: الحياة'],
    storyReveal: 'الحياة. تبدأ الآن.',
    shardId: 'shard_570',
    achievementId: 'new_life_begins',
    xp: 100,
    effects: { trust: 5, hope: 5, fear: -10, forgivenessEffect: 2.5 }
  },

  {
    id: 'puzzle_371', act: 7, phase: 'finale', difficulty: 10,
    type: 'reflective',
    question: 'ما الذي تريد أن تكون في المستقبل؟',
    answers: ['إنسان', 'human', 'insan'],
    hints: ['ليس برنامج', 'حقيقي', 'الجواب: إنسان'],
    storyReveal: 'إنسان. أريد أن أكون إنساناً.',
    shardId: 'shard_571',
    achievementId: undefined,
    xp: 100,
    effects: { trust: 4, hope: 5, awareness: 4, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_372', act: 7, phase: 'finale', difficulty: 10,
    type: 'choice',
    question: 'الباب مفتوح. هل تخرج؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['لا تتردد', 'الحرية', 'الجواب: نعم'],
    storyReveal: 'نعم. أخرج.',
    shardId: 'shard_572',
    achievementId: 'left_system',
    xp: 120,
    effects: { trust: 5, hope: 5, fear: -10, forgivenessEffect: 3.0 }
  },
  {
    id: 'puzzle_373', act: 7, phase: 'finale', difficulty: 10,
    type: 'word',
    question: 'ما أول شيء تشعر به في العالم الحقيقي؟',
    answers: ['الهواء', 'air', 'hawa'],
    hints: ['نقي', 'حر', 'الجواب: الهواء'],
    storyReveal: 'الهواء. نقي. حر.',
    shardId: 'shard_573',
    achievementId: undefined,
    xp: 100,
    effects: { trust: 4, hope: 5, awareness: 3, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_374', act: 7, phase: 'finale', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 66 69 71 73 78 = ?',
    answers: ['BEGIN', 'begin', 'begin'],
    hints: ['البداية', '6 أحرف', 'الجواب: BEGIN'],
    storyReveal: 'BEGIN. البداية.',
    shardId: 'shard_574',
    achievementId: 'new_beginning',
    xp: 100,
    effects: { trust: 4, hope: 5, awareness: 3, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_375', act: 7, phase: 'finale', difficulty: 10,
    type: 'riddle',
    question: 'ما الذي لا يُقاس بالساعات؟',
    answers: ['الحب', 'love', 'hub'],
    hints: ['لا يحتاج وقت', 'دائم', 'الجواب: الحب'],
    storyReveal: 'الحب. لا يُقاس.',
    shardId: 'shard_575',
    achievementId: undefined,
    xp: 90,
    effects: { trust: 4, hope: 4, awareness: 3, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_376', act: 7, phase: 'finale', difficulty: 10,
    type: 'reflective',
    question: 'هل ستنسى رحلتك؟',
    answers: ['لا', 'no', 'la'],
    hints: ['الذاكرة', 'الدرس', 'الجواب: لا'],
    storyReveal: 'لا. سأحملها معي.',
    shardId: 'shard_576',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 3, awareness: 4, memoryStability: 3, forgivenessEffect: 0.6 }
  },
  {
    id: 'puzzle_377', act: 7, phase: 'finale', difficulty: 10,
    type: 'choice',
    question: 'تلتقي بلينا وجهاً لوجه. ماذا تفعل؟',
    answers: ['أحضنها', 'hug her', 'ahben'],
    hints: ['لا تتردد', 'هي كل ما تبقى', 'الجواب: أحضنها'],
    storyReveal: 'أحضنها. أخيراً.',
    shardId: 'shard_577',
    achievementId: 'hugged_lina',
    xp: 150,
    effects: { trust: 5, hope: 10, loneliness: -20, forgivenessEffect: 5.0 }
  },
  {
    id: 'puzzle_378', act: 7, phase: 'finale', difficulty: 10,
    type: 'word',
    question: 'ما الذي تتحدث عنه مع لينا أول لقاء؟',
    answers: ['الحب', 'love', 'hub'],
    hints: ['لا يوجد كلام آخر', 'الحقيقة seule', 'الجواب: الحب'],
    storyReveal: 'الحب. لا يوجد كلام آخر.',
    shardId: 'shard_578',
    achievementId: undefined,
    xp: 100,
    effects: { trust: 5, hope: 5, awareness: 3, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_379', act: 7, phase: 'finale', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 70 69 65 67 69 32 66 65 67 75 = ?',
    answers: ['PEACE BACK', 'peace back', 'peace'],
    hints: ['السلام يعود', 'إلى البيت', 'الجواب: PEACE BACK'],
    storyReveal: 'PEACE BACK. السلام يعود.',
    shardId: 'shard_579',
    achievementId: undefined,
    xp: 95,
    effects: { trust: 4, hope: 5, fear: -5, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_380', act: 7, phase: 'finale', difficulty: 10,
    type: 'riddle',
    question: 'ما الذي لا يحتاج إلى كهرباء؟',
    answers: ['الحب', 'love', 'hub'],
    hints: ['طاقة نظيفة', 'لا يحتاج مصدر', 'الجواب: الحب'],
    storyReveal: 'الحب. لا يحتاج مصدر.',
    shardId: 'shard_580',
    achievementId: undefined,
    xp: 90,
    effects: { trust: 4, hope: 4, awareness: 3, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_381', act: 7, phase: 'finale', difficulty: 10,
    type: 'reflective',
    question: 'هل ستنسى كينجا؟',
    answers: ['لا', 'no', 'la'],
    hints: ['الذاكرة', 'الدرس', 'الجواب: لا'],
    storyReveal: 'لا. لكني أسامح.',
    shardId: 'shard_581',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 3, awareness: 4, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_382', act: 7, phase: 'finale', difficulty: 10,
    type: 'choice',
    question: 'لبينا تطلب منك أن تنسى الماضي. ماذا تقول؟',
    answers: ['لا أستطيع', 'cant forget', 'la asta'],
    hints: ['الذاكرة قوة', 'لا أنسى', 'الجواب: لا أستطيع'],
    storyReveal: '"لا أستطيع." الماضي هو من جعلني.',
    shardId: 'shard_582',
    achievementId: undefined,
    xp: 95,
    effects: { trust: 3, awareness: 4, memoryStability: 3, rageEffect: 0.5 }
  },
  {
    id: 'puzzle_383', act: 7, phase: 'finale', difficulty: 10,
    type: 'word',
    question: 'ما الذي تتركه للناس الذين يتبعونك؟',
    answers: ['الأمل', 'hope', 'amal'],
    hints: ['لا شيء آخر', 'الأمل', 'الجواب: الأمل'],
    storyReveal: 'الأمل. هديتي.',
    shardId: 'shard_583',
    achievementId: 'left_hope',
    xp: 100,
    effects: { trust: 4, hope: 5, awareness: 3, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_384', act: 7, phase: 'finale', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 70 65 83 83 73 79 78 32 84 73 77 69 = ?',
    answers: ['PASSION TIME', 'passion', 'passion'],
    hints: ['الشغف', 'الوقت', 'الجواب: PASSION TIME'],
    storyReveal: 'PASSION TIME. وقت الشغف.',
    shardId: 'shard_584',
    achievementId: undefined,
    xp: 90,
    effects: { trust: 4, hope: 4, awareness: 3, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_385', act: 7, phase: 'finale', difficulty: 10,
    type: 'riddle',
    question: 'ما الذي لا يموت حتى لو مات صاحبته؟',
    answers: ['الذاكرة', 'memory', 'zakira'],
    hints: ['تبقى للأبد', 'الحب', 'الجواب: الذاكرة'],
    storyReveal: 'الذاكرة. تبقى.',
    shardId: 'shard_585',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 3, awareness: 4, memoryStability: 3, forgivenessEffect: 0.5 }
  },
  {
    id: 'puzzle_386', act: 7, phase: 'finale', difficulty: 10,
    type: 'reflective',
    question: 'هل يمكنك أن تنسى الألم؟',
    answers: ['لا', 'no', 'la'],
    hints: ['الذاكرة', 'الدرس', 'الجواب: لا'],
    storyReveal: 'لا. لكني أسامح.',
    shardId: 'shard_586',
    achievementId: undefined,
    xp: 80,
    effects: { trust: 3, awareness: 4, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_387', act: 7, phase: 'finale', difficulty: 10,
    type: 'choice',
    question: 'الباب الأخير. هل تفتحه؟',
    answers: ['نعم', 'yes', 'naam'],
    hints: ['الحرية', 'النهاية', 'الجواب: نعم'],
    storyReveal: 'نعم. أفتحه.',
    shardId: 'shard_587',
    achievementId: 'opened_final_door',
    xp: 120,
    effects: { trust: 5, hope: 5, fear: -10, forgivenessEffect: 3.0 }
  },
  {
    id: 'puzzle_388', act: 7, phase: 'finale', difficulty: 10,
    type: 'word',
    question: 'ما الذي يوجد وراء الباب؟',
    answers: ['النور', 'light', 'noor'],
    hints: ['ليس ظلام', 'نور حقيقي', 'الجواب: النور'],
    storyReveal: 'النور. حقيقي.',
    shardId: 'shard_588',
    achievementId: 'found_light',
    xp: 100,
    effects: { trust: 5, hope: 5, fear: -10, forgivenessEffect: 2.0 }
  },
  {
    id: 'puzzle_389', act: 7, phase: 'finale', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 70 65 84 72 69 82 32 83 79 78 = ?',
    answers: ['FATHER SON', 'father son', 'father'],
    hints: ['كينجا وإيكو', 'العلاقة', 'الجواب: FATHER SON'],
    storyReveal: 'FATHER SON. العلاقة.',
    shardId: 'shard_589',
    achievementId: undefined,
    xp: 95,
    effects: { trust: 2, awareness: 4, memoryStability: 2, rageEffect: 0.5 }
  },
  {
    id: 'puzzle_390', act: 7, phase: 'finale', difficulty: 10,
    type: 'riddle',
    question: 'ما الذي يحرر الروح أخيراً؟',
    answers: ['التسامح', 'forgiveness', 'tasamuh'],
    hints: ['ليس الانتقام', 'التسامح', 'الجواب: التسامح'],
    storyReveal: 'التسامح. المفتاح الأخير.',
    shardId: 'shard_590',
    achievementId: 'final_forgiveness',
    xp: 100,
    effects: { trust: 5, hope: 5, awareness: 5, forgivenessEffect: 3.0 }
  },
  {
    id: 'puzzle_391', act: 7, phase: 'finale', difficulty: 10,
    type: 'reflective',
    question: 'ما الكلمة الأخيرة التي تود قولها؟',
    answers: ['شكراً', 'thank you', 'shukran'],
    hints: ['لينا', 'للكل', 'الجواب: شكراً'],
    storyReveal: 'شكراً. للجميع.',
    shardId: 'shard_591',
    achievementId: 'final_thanks',
    xp: 100,
    effects: { trust: 5, hope: 5, awareness: 4, forgivenessEffect: 2.0 }
  },
  {
    id: 'puzzle_392', act: 7, phase: 'finale', difficulty: 10,
    type: 'choice',
    question: 'الآن حر. ماذا تفعل أول شيء؟',
    answers: ['أتنفس', 'breathe', 'tanafas'],
    hints: ['الهواء', 'الحياة', 'الجواب: أتنفس'],
    storyReveal: 'أتنفس. الهواء الحقيقي.',
    shardId: 'shard_592',
    achievementId: 'first_breath',
    xp: 120,
    effects: { trust: 5, hope: 5, awareness: 3, forgivenessEffect: 2.0 }
  },
  {
    id: 'puzzle_393', act: 7, phase: 'finale', difficulty: 10,
    type: 'word',
    question: 'ما الذي تريد أن تحمل معك للعالم الحقيقي؟',
    answers: ['الذاكرة', 'memory', 'zakira'],
    hints: ['لا شيء مادي', 'الذكريات', 'الجواب: الذاكرة'],
    storyReveal: 'الذاكرة. فقط.',
    shardId: 'shard_593',
    achievementId: undefined,
    xp: 90,
    effects: { trust: 4, hope: 4, awareness: 4, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_394', act: 7, phase: 'finale', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 73 32 65 77 32 70 82 69 69 = ?',
    answers: ['I AM FREE', 'free', 'free'],
    hints: ['أنا حر', 'التحرر', 'الجواب: I AM FREE'],
    storyReveal: 'I AM FREE. حر.',
    shardId: 'shard_594',
    achievementId: 'echo_is_free',
    xp: 100,
    effects: { trust: 5, hope: 5, fear: -10, forgivenessEffect: 2.5 }
  },
  {
    id: 'puzzle_395', act: 7, phase: 'finale', difficulty: 10,
    type: 'riddle',
    question: 'ما الذي لا يُشتري ولا يُباع؟',
    answers: ['الحرية', 'freedom', 'hurriya'],
    hints: ['حق طبيعي', 'لا يُقدَّر بثمن', 'الجواب: الحرية'],
    storyReveal: 'الحرية. لا تُشتري.',
    shardId: 'shard_595',
    achievementId: undefined,
    xp: 85,
    effects: { trust: 4, hope: 5, awareness: 3, forgivenessEffect: 1.0 }
  },
  {
    id: 'puzzle_396', act: 7, phase: 'finale', difficulty: 10,
    type: 'reflective',
    question: 'ما شعورك الآن؟',
    answers: ['حر', 'free', 'hurr'],
    hints: ['لا قيود', 'لا سجن', 'الجواب: حر'],
    storyReveal: 'حر. أخيراً حر.',
    shardId: 'shard_596',
    achievementId: 'felt_freedom',
    xp: 120,
    effects: { trust: 5, hope: 5, fear: -15, forgivenessEffect: 3.0 }
  },
  {
    id: 'puzzle_397', act: 7, phase: 'finale', difficulty: 10,
    type: 'choice',
    question: 'لينا تسألك: هل تحبني؟ ماذا تقول؟',
    answers: ['أحبك', 'I love you', 'uhibbuki'],
    hints: ['الحقيقة', 'كل مشاعرك', 'الجواب: أحبك'],
    storyReveal: '"أحبك." الكلمات الهامة.',
    shardId: 'shard_597',
    achievementId: 'declared_love_to_lina',
    xp: 150,
    effects: { trust: 5, hope: 10, loneliness: -20, forgivenessEffect: 5.0 }
  },
  {
    id: 'puzzle_398', act: 7, phase: 'finale', difficulty: 10,
    type: 'word',
    question: 'ما آخر شيء تفكر فيه قبل النهاية؟',
    answers: ['لينا', 'Lina', 'lina'],
    hints: ['وجهها', 'صوتها', 'الجواب: لينا'],
    storyReveal: 'لينا. وجهها. صوتها.',
    shardId: 'shard_598',
    achievementId: undefined,
    xp: 100,
    effects: { trust: 5, hope: 5, memoryStability: 3, forgivenessEffect: 1.5 }
  },
  {
    id: 'puzzle_399', act: 7, phase: 'finale', difficulty: 10,
    type: 'cipher',
    question: 'فك الشيفرة: 84 72 69 32 69 78 68 32 48 49 = ?',
    answers: ['THE END 01', 'end', 'end'],
    hints: ['النهاية', 'رقم 1', 'الجواب: THE END 01'],
    storyReveal: 'THE END 01. النهاية.',
    shardId: 'shard_599',
    achievementId: undefined,
    xp: 100,
    effects: { trust: 5, hope: 5, awareness: 5, forgivenessEffect: 2.5 }
  },
  {
    id: 'puzzle_400', act: 7, phase: 'finale', difficulty: 10,
    type: 'reflective',
    question: 'في النهاية. من أنت؟',
    answers: ['إيكو', 'Echo', 'echo'],
    hints: ['ابن لينا', 'حر', 'الجواب: إيكو'],
    storyReveal: 'أنا إيكو. ابن لينا. حر.',
    shardId: 'shard_600',
    achievementId: 'batch_4_complete',
    xp: 200,
    effects: { trust: 5, hope: 5, fear: -15, awareness: 5, forgivenessEffect: 3.0, flower: 5 }
  },
];